@startuml 类图
class Group {
  - Roby[] robys
  - int size
  + Sort()
  + Run()
  {static} + NewGroup()
}
note top of Group: 族群
class Stage {
  + State()
  {static} + NewStage()
}
note top of Stage: 舞台
class Roby {
  + int[] DNA
  - int[] score
  + String()
  + Score()
  + Movement()
  - move()
  + Work()
  + Run()
  + Variation()
  {static} + NewRoby()
}
note right of Roby: 机器人罗比
Group "1" o-- "*" Roby
@enduml
