@startuml 类图
class Stage {

}
note top of Stage: 舞台
note top of RandQueue: 随机队列
class Roby {
  + int[] DNA
  - int score
  run()
}
note top of Roby: 机器人罗比
note top of Group: 族群
' IDModel <|-- Order
@enduml
